### ISSUE TITLE
what version of Pytorch to use，询问作者使用的pytroch版本。

### ISSUE THREAD

**Issue by xxddccaa** [ChenWu98/cycle-diffusion#25]
run
```
python -m torch.distributed.launch --nproc_per_node 1 --master_port 1498 main.py --seed $SEED --cfg experiments/$RUN_NAME.cfg --run_name $RUN_NAME$SEED --logging_strategy steps --logging_first_step true --logging_steps 4 --evaluation_strategy steps --eval_steps 50 --metric_for_best_model CLIPEnergy --greater_is_better false --save_strategy steps --save_steps 50 --save_total_limit 1 --load_best_model_at_end --gradient_accumulation_steps 4 --num_train_epochs 0 --adafactor false --learning_rate 1e-3 --do_eval --output_dir output/$RUN_NAME$SEED --overwrite_output_dir --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --eval_accumulation_steps 4 --ddp_find_unused_parameters true --verbose true

```

an error occurred:

```
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

this seems to be due to the Pytorch version, would you tell me the version of Pytorch you are using.

这似乎是Pytorch版本导致的，你可以说一下你使用的pytorch版本吗？

complete logs:
```
833 256823.1875
834 262594.46875
835 269648.78125
836 278420.9375
837 289375.3125
838 301356.34375
839 319525.6875
840 336861.6875
841 366365.5
842 400465.03125
843 446937.90625
844 522279.5
845 637578.5
846 847171.375
847 1310254.0
848 2956609.0
at tensor([[[[0.7883]]]], device='cuda:0')
1it [00:50, 50.43s/it]
1it [00:00,  4.20it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.02it/s]
Traceback (most recent call last):
  File "/ssd/xiedong/home/InST-main/cycle-diffusion-main/main.py", line 160, in <module>
    main()
  File "/ssd/xiedong/home/InST-main/cycle-diffusion-main/main.py", line 128, in main
    metrics = trainer.evaluate(
  File "/ssd/xiedong/home/InST-main/cycle-diffusion-main/trainer/trainer.py", line 1047, in evaluate
    metrics, num_samples = eval_loop(
  File "/ssd/xiedong/home/InST-main/cycle-diffusion-main/trainer/trainer.py", line 872, in evaluation_loop
    metrics = self.compute_metrics(images,
  File "/ssd/xiedong/home/InST-main/cycle-diffusion-main/evaluation/multi_task.py", line 65, in evaluate
    summary_tmp = evaluator.evaluate(**eval_kwargs, split=split)
  File "/ssd/xiedong/home/InST-main/cycle-diffusion-main/evaluation/translate_to_dog.py", line 81, in evaluate
    kid_score = fid.compute_kid(
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/cleanfid/fid.py", line 356, in compute_kid
    feat_model = build_feature_extractor(mode, device)
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/cleanfid/features.py", line 42, in build_feature_extractor
    feat_model = feature_extractor(name="torchscript_inception", resize_inside=False, device=device)
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/cleanfid/features.py", line 21, in feature_extractor
    model = InceptionV3W(path, download=True, resize_inside=resize_inside).to(device)
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/cleanfid/inception_torchscript.py", line 35, in __init__
    self.base = torch.jit.load(path).eval()
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:
wandb: Synced translate_afhqwild256_to_afhqdog256_ddim_eta0142: https://wandb.ai/xxcc/graphql/runs/13afq6e4
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230807_152834-13afq6e4/logs
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2859870) of binary: /ssd/xiedong/miniconda3/envs/generative_prompt/bin/python
Traceback (most recent call last):
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/ssd/xiedong/miniconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-07_15:29:47
  host      : gpu20
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2859870)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
  
  ```

**Comment by xxddccaa** [comment]
I gave two files myself:
./stargan-v2/data/test/wild/cat512512.jpg
./stargan-v2/data/test/dog/dog512512.jpg

I see this sentence in the error log:
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

If I make the experiment correctly, I should be able to see the artifact image in Wandb, right?
如果我一切操作顺序，我在Wandb是可以看到artifact image的吧，这是对的吗。

**Comment by xxddccaa** [comment]
to add, I am run these few command:

export CUDA_VISIBLE_DEVICES=0
export RUN_NAME=translate_afhqwild256_to_afhqdog256_ddim_eta01
export SEED=42
python -m torch.distributed.launch --nproc_per_node 1 --master_port 1498 main.py --seed $SEED --cfg experiments/$RUN_NAME.cfg --run_name $RUN_NAME$SEED --logging_strategy steps --logging_first_step true --logging_steps 4 --evaluation_strategy steps --eval_steps 50 --metric_for_best_model CLIPEnergy --greater_is_better false --save_strategy steps --save_steps 50 --save_total_limit 1 --load_best_model_at_end --gradient_accumulation_steps 4 --num_train_epochs 0 --adafactor false --learning_rate 1e-3 --do_eval --output_dir output/$RUN_NAME$SEED --overwrite_output_dir --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --eval_accumulation_steps 4 --ddp_find_unused_parameters true --verbose true

**Comment by ChenWu98** [comment]
This seems to be the dependency issue of [cleanfid](https://github.com/GaParmar/clean-fid). They used 1.9 ([link](https://github.com/GaParmar/clean-fid/blob/main/environment.yml)), but I remember I was using something like 12.1. 

If you do not want to use cleanfid, you can simply remove the kid_score in translate_to_dog.py.

**Comment by xxddccaa** [comment]
感谢指导，已经成功运行。

```
843 446937.90625
844 522279.5
845 637578.5
846 847171.375
847 1310254.0
848 2956609.0
at tensor([[[[0.7883]]]], device='cuda:0')
1it [00:57, 57.16s/it]
1it [00:00,  9.61it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.15it/s]
***** eval metrics *****
  _runtime                = 0:01:07.00
  _timestamp              = 1691396206
  eval/avr                =     21.649
  eval/runtime            =    58.0648
  eval/samples_per_second =      0.017
  eval/steps_per_second   =      0.017
  eval/translate/l2       =    44.3614
  eval/translate/psnr     =    19.9959
  eval/translate/ssim     =     0.5898
  eval/weighted_loss      =        0.0
  eval_samples            =          1
trainer <trainer.trainer.Trainer object at 0x7f843c044fa0>
wandb: Waiting for W&B process to finish... (success).
wandb:
wandb:
wandb: Run history:
wandb:                eval/avr ▁
wandb:            eval/runtime ▁
wandb: eval/samples_per_second ▁
wandb:   eval/steps_per_second ▁
wandb:       eval/translate/l2 ▁
wandb:     eval/translate/psnr ▁
wandb:     eval/translate/ssim ▁
wandb:      eval/weighted_loss ▁
wandb:
wandb: Run summary:
wandb:                eval/avr 21.64904
wandb:            eval/runtime 58.0648
wandb: eval/samples_per_second 0.017
wandb:   eval/steps_per_second 0.017
wandb:       eval/translate/l2 44.36137
wandb:     eval/translate/psnr 19.99591
wandb:     eval/translate/ssim 0.58984
wandb:      eval/weighted_loss 0.0
wandb:
wandb: Synced translate_afhqwild256_to_afhqdog256_ddim_eta0142: https://wandb.ai/xxcc/graphql/runs/2r1fk0bl
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230807_161539-2r1fk0bl/logs
```
