### ISSUE TITLE
torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 613558) of binary:

### ISSUE THREAD

**Issue by giovanlee** [ChenWu98/cycle-diffusion#28]
#### During Unpaired image-to-image translation with diffusion models trained on two domains task, I have error code as below. How can I fix it?
```python
torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 613558) of binary: /home/*****/anaconda3/envs/joohoon_cd/bin/python
Traceback (most recent call last):
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/*****/anaconda3/envs/generative_prompt/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
```

Thanks

**Comment by ChenWu98** [comment]
Hi, any chance I can see the full error log? Thanks!

**Comment by giovanlee** [comment]
Here is full error log. joohoon_cd is same as generative_prompt.
```python
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/giovanlee97/workspace/cycle-diffusion/main.py", line 151, in <module>
    main()
  File "/home/giovanlee97/workspace/cycle-diffusion/main.py", line 65, in main
    training_args, = parser.parse_args_into_dataclasses()
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/site-packages/transformers/hf_argparser.py", line 223, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local-rank=0']
[2024-01-25 06:01:40,777] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2029188) of binary: /home/giovanlee97/anaconda3/envs/joohoon_cd/bin/python
Traceback (most recent call last):
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/giovanlee97/anaconda3/envs/joohoon_cd/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-25_06:01:40
  host      : gpu04.ontacthealth.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2029188)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Thanks!

**Comment by ChenWu98** [comment]
I guess it’s related to package versions. You may find this helpful: https://github.com/huggingface/transformers/issues/22171

**Comment by giovanlee** [comment]
No error anymore, Thanks :)
